---
version: '3'

tasks:
  default:
    silent: true
    cmd: task -l

  test:
    desc: Run all tests
    cmds:
      - go test -count=1 ./... # disables caching
    silent: false

  snapshot:
    desc: Build a snapshot
    cmds:
      - goreleaser build --snapshot --single-target --clean

  lint: 
    desc: Run all linters
    cmds:
      - golangci-lint run
    silent: false

  gifs:
    desc: Generate all vhs gifs for the README
    cmds:
      - vhs download.tape 
      - vhs list.tape
