---
version: '3'

tasks:
  default:
    silent: true
    cmd: task -l

  test:
    desc: Run all tests
    cmds:
      - go test -count=1 ./... # disables caching
    silent: false

  snapshot:
    desc: Build a snapshot
    cmds:
      - goreleaser build --snapshot --single-target --clean

  lint: 
    desc: Run all linters
    cmds:
      - golangci-lint run
      - go fmt ./...
    silent: false

  gifs:
    desc: Generate all vhs gifs for the README
    cmds:
      - vhs download.tape 
      - vhs list.tape

  readme:
    desc: |
      Convert the README.md to ModDB-friendly HTML
    dir: docs
    preconditions:
      - which pandoc
      - test -f README.md
    cmds:
      - pandoc README.md -o README.html  

  package:
    desc: |
      Fetches the latest vsmod Windows release and renames it to include the version for the ModDB
    silent: true
    preconditions:
      - which zip
      - test -d dist
    cmds:
      - |
        rel=$(curl -s https://api.github.com/repos/stevewm/vsmod/releases/latest | jq -r .tag_name)
        url=$(curl -s https://api.github.com/repos/stevewm/vsmod/releases/latest | jq -r '.assets[] | select(.name=="vsmod_Windows_x86_64.zip") | .browser_download_url')
        curl -sL "$url" -o "dist/vsmod_Windows_x86_64_${rel}.zip"
