---
name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checks:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24.x

      - name: lint
        uses: golangci/golangci-lint-action@v8

      - name: test
        run: go test ./...
