---
name: Create new tag

on:
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      DRY_RUN:
        description: Whether to perform a dry run (no tag pushed)
        required: true
        default: false
        type: boolean

jobs:
  tag:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: ${{ github.event.inputs.DRY_RUN }}
