name: Test config file

on:
  pull_request: 
    branches: [main]
  workflow_dispatch:

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        command: [list, download]
        platforms: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platforms }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: create snapshot
        id: goreleaser
        uses: goreleaser/goreleaser-action@v6
        with: 
          version: latest
          args: build --snapshot --clean --single-target

      - name: output
        env:
          ARTIFACTS: ${{ steps.goreleaser.outputs.artifacts }}
        run: |
            echo $ARTIFACTS

      - name: get binary path
        uses: cloudposse/github-action-jq@0.4.0
        id: jq
        with: 
          compact: true
          input: ${{ steps.goreleaser.outputs.artifacts }}
          raw-output: true
          script: |-
            .[] | select(.name=="vsmod" or .name=="vsmod.exe") | .path

      - name: vsmod ${{ matrix.command }}
        run: ${{ github.workspace }}/${{ steps.jq.outputs.output }} ${{ matrix.command }} --file ./examples/mods.yaml --debug
